### ISSUE TITLE
Suggestion - remove MobxAutorunSyncDirective

### ISSUE THREAD

**Issue by kubk** [mobxjs/mobx-angular#102]
This directive was deprecated in 2017. I think it can be safely removed :) This is a BC break so we'll need to release a new major version of `mobx-angular`.

https://github.com/mobxjs/mobx-angular/commit/2a36c1f6dbf6c22dfb858c4678aaaebd7e7b30a4#diff-8e822c76c16e6597b602bc136d44e18b

**Comment by adamkleingit** [comment]
I agree. Will do
