### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by LifeIsStrange** [mobxjs/mobx-angular#124]
Please! (this project is amazing! )

**Comment by kubk** [comment]
Hi, have you tried mobx-angular with Angular 10? Which errors have you encountered?

**Comment by LifeIsStrange** [comment]
@kubk no I've not tried it yet but the Readme only mention up to version 9.

**Comment by LifeIsStrange** [comment]
so I tried it on Angular 10 and it's working fine!
