### ISSUE TITLE
New Mobx version

### ISSUE THREAD

**Issue by nicolidin** [mobxjs/mobx-angular#125]
As Mobx is now in 6.0.1, this repository should add in the ReadMe and in the examples (should update mobx version) `makeObservable(this)` or `makeAutoObservable(this)` (if no decorators) in the constructor. If decorators is used  `"useDefineForClassFields": true` should be added to in tsconfig.json too.

(if you validate I can create the pr)

**Comment by adamkleingit** [comment]
True,
@nicolidin care to make a PR?
That would be very helpful for the repo and the community. Thanks!

**Comment by EVASIVE** [comment]
@adamkleingit I am also faced with inconsistence of mobx-angular example and mobx documentation, so I created PR with these changes
#138

**Comment by SimonTouitou** [comment]
Thanks @EVASIVE, This has been merged (#138).
Closing.
