### ISSUE TITLE
Support Angular 10 and above

### ISSUE THREAD

**Issue by th0r** [mobxjs/mobx-angular#127]
Current version of this package supports only v9:
https://github.com/mobxjs/mobx-angular/blob/6bf39d7faa8e2050c23aacdfd9fefbd56e04c1ff/projects/mobx-angular/package.json#L6-L7

It would be great to also support Angular 10 and above.

**Comment by popec** [comment]
We're on Angular 11 and getting JS error with aot; true
`TypeError: t.make_ is not a function`
Any chances for Angular 11 support with aot: true ?

**Comment by reidkornman** [comment]
Sticking to the root of this ask... when will Angular 11 support be consider/added?

**Comment by adamkleingit** [comment]
Anyone wants to try and solve this and open a PR?
@popec @reidkornman @th0r 
It would be much appreciated. Thanks!

**Comment by popec** [comment]
It's not helping, same thing happens after building app with buildOptimizer: true in angular.json as before. 
It's probably mobx itself not being ok with uglify maybe?
