### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by adamkleingit** [mobxjs/mobx-angular#141]
Hi!
Although this library is very small and simple, it still needs a little bit of attention here and there.  

If there's anyone from the community that's willing to step up, we would be happy to add you to the MobX organization. Just reply to this issue

**Comment by adamkleingit** [comment]
Tagging @EVASIVE @OmerGronich  @SimonTouitou  @kubk @nunocastromartins in case it's relevant for you

**Comment by OmerGronich** [comment]
@adamkleingit  I would love to help maintain this package however I can, love it and use it everyday. 👍

**Comment by SimonTouitou** [comment]
Same goes here.
Mobx is my preferred state management lib.
I'll help as much as I can.

**Comment by adamkleingit** [comment]
@OmerGronich @SimonTouitou cool!

Let me see how we can add you to Github and NPM so you can push code / approve PRs / publish versions

**Comment by EVASIVE** [comment]
@adamkleingit I would be glad to help as well.

**Comment by adamkleingit** [comment]
@mweststrate - can you add these amazing fellas to the organization? Thanks

**Comment by adamkleingit** [comment]
@OmerGronich @SimonTouitou @EVASIVE please send your NPM users as well so you can help publish new versions

**Comment by SimonTouitou** [comment]
tgate

**Comment by EVASIVE** [comment]
@adamkleingit evazive

**Comment by mweststrate** [comment]
Sorry for the late follow up folks! Was on holiday so didn't have elevated access :). Invite have been send. Note that I don't have npm access, so that needs to be granted by @adamkleingit  (`npm owner add tgate mobx-angular` etc)

**Comment by adamkleingit** [comment]
@EVASIVE @SimonTouitou sent invite to join the organization on npm (500tech). Once you approve I'll give you access to the package

**Comment by OmerGronich** [comment]
> @OmerGronich @SimonTouitou @EVASIVE please send your NPM users as well so you can help publish new versions

gronichomer

**Comment by Chuckv01** [comment]
@mweststrate @adamkleingit I'd love to help maintain this package!

An organization I am apart of uses mobx-angular heavily and I'd be happy to help review / publishing to npm on PRs like https://github.com/mobxjs/mobx-angular/pull/171

My npm username is `chuckv01`.

**Comment by adamkleingit** [comment]
Sure! @mweststrate can you add him to the github organization?

**Comment by adamkleingit** [comment]
@Chuckv01  I Invited you to npm

**Comment by mweststrate** [comment]
@Chuckv01 just send a GH invite as well

**Comment by Chuckv01** [comment]
@adamkleingit @mweststrate thanks! Accepted both invites and I am setup to help 👍

**Comment by roypeled** [comment]
Hey @adamkleingit , I would be happy to help.

**Comment by alwleedamado** [comment]
It will be a pleasure to help.
