### ISSUE TITLE
Generic type 'IReactionOptions' requires 1 type argument(s).

### ISSUE THREAD

**Issue by biaogebusy** [mobxjs/mobx-angular#142]
Hi, i use github action build was normal before, today show the error.

Error: node_modules/mobx-angular/lib/mobx-reaction.directive.d.ts:9:26 - error TS2314: Generic type 'IReactionOptions' requires 1 type argument(s).
mobxReactionOptions: IReactionOptions;
Error: Process completed with exit code 1.

package.json:
"dependencies": {
    "@amap/amap-jsapi-loader": "0.0.7",
    "@angular/animations": "^11.0.2",
    "@angular/cdk": "^11.2.9",
    "@angular/common": "~11.0.1",
    "@angular/compiler": "~11.0.1",
    "@angular/core": "~11.0.1",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~11.0.1",
    "@angular/material": "^11.0.1",
    "@angular/platform-browser": "~11.0.1",
    "@angular/platform-browser-dynamic": "~11.0.1",
    "@angular/router": "~11.0.1",
    "@ckeditor/ckeditor5-angular": "^2.0.2",
    "@ckeditor/ckeditor5-build-classic": "^29.1.0",
    "@types/lodash-es": "^4.17.4",
    "@types/video.js": "^7.3.15",
    "angular-count-to": "^0.0.3",
    "angulartics2": "^10.0.0",
    "gsap": "^3.6.0",
    "hammerjs": "^2.0.8",
    "highlight.js": "^10.7.2",
    "lodash-es": "^4.17.20",
    "material-design-icons": "^3.0.1",
    "mobx": "^6.3.3",
    "mobx-angular": "^4.1.0",
    "ng-dynamic-component": "^8.0.1",
    "ngx-lightbox": "^2.3.0",
    "ngx-pagination": "^5.1.0",
    "ngx-pipes": "^2.7.5",
    "ngx-swiper-wrapper": "^10.0.0",
    "ngx-webstorage": "^7.0.1",
    "rxjs": "~6.6.0",
    "shufflejs": "^5.3.0",
    "svelte": "^3.37.0",
    "swiper": "^6.5.0",
    "tslib": "^2.0.0",
    "video.js": "^7.11.8",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@amap/amap-jsapi-types": "0.0.8",
    "@angular-devkit/build-angular": "~0.1100.2",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.0.1",
    "@types/gsap": "^1.20.2",
    "@types/jasmine": "~3.6.0",
    "@types/lodash-es": "^4.17.4",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }

what's the issue? Thanks.

**Comment by thesleort** [comment]
I have the same issue with `"@angular/cli": "12.2.4"` and `"@angular/core": "12.2.4"`  etc.

**Comment by thesleort** [comment]
I fixed it by downgrading mobx to `6.3.2` from `6.3.3`

**Comment by Galeups** [comment]
> I fixed it by downgrading mobx to `6.3.2` from `6.3.3`

But it doesn't work for me

```
    "mobx": "^6.3.2",
    "mobx-angular": "^4.3.0",
```

maybe you didn`t import MobxAngularModule to the AppModule?

**Comment by biaogebusy** [comment]
I fixed it by:
`
"mobx": "6.2.0",
"mobx-angular": "^4.2.0",
`

**Comment by SimonTouitou** [comment]
Fixed in new version.
#Closed
