### ISSUE TITLE
mobx-angular imports broken since 4.5.0

### ISSUE THREAD

**Issue by Korsarro69** [mobxjs/mobx-angular#162]
I must upgrade mobx-angular to 4.5.0 to update to Angular 13. After installing the last version, the structure of the package has changed :

Before :
mobx-angular > lib > mobx-angular.module.d.ts

After
mobx-angular > src > lib > mobx-angular.module.d.ts

It's like the package wasn't compiled, and all "MobxAngularModule" imports are broken. the command "npm install" works, but the start fail

**Comment by SimonTouitou** [comment]
Can you refer to this commit: https://github.com/mobxjs/mobx-angular/commit/209004520b12992e5d7fdcc98454d27f3a31364a and change package.json dependencies to the old dependencies before the commit and tell us if it works that way?

**Comment by Korsarro69** [comment]
Well that works but I need this commit to upgrade my angular version, cf #152. Could you rebuild the tag 4.5.0 ?

**Comment by julien-boucly-needone** [comment]
Hello
I encounter a similar problem, I have to upgrade my project's angular version, and when I update the package I end up with this error at each place where Mobx-angular is imported => 

> 
> Cannot find module 'mobx-angular' or its corresponding type declarations.
> 
> import { action, observable } from 'mobx-angular';

**Comment by SimonTouitou** [comment]
@Korsarro69 @julien-boucly-needone Thank you for your feedback.
Package has been properly rebuilt as v4.5.1 (due to rebuild rules).
Waiting for your confirmation.

**Comment by Korsarro69** [comment]
I confirm this issue is fixed with the tag v4.5.1. Thank you for your work

**Comment by julien-boucly-needone** [comment]
> @Korsarro69 @julien-boucly-needoneMerci pour votre avis. Le package a été correctement reconstruit en tant que v4.5.1 (en raison des règles de reconstruction). J'attends votre confirmation.

Awesome thank you for the responsiveness!! It fixed all my problems ! Thanks !
