### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by Chuckv01** [mobxjs/mobx-angular#164]
Any plans to support Angular 14? https://github.com/mobxjs/mobx-angular/blob/master/projects/mobx-angular/package.json#L6-L7

**Comment by Chuckv01** [comment]
PR opened here https://github.com/mobxjs/mobx-angular/pull/165

**Comment by simonto-tr** [comment]
@Chuckv01 Have you tested your PR locally?

**Comment by Chuckv01** [comment]
@simonto-tr yes, I have just tested mobx-angular locally and can confirm it works in Angular 14.
