### ISSUE TITLE
Any plans to support Angular 17?

### ISSUE THREAD

**Issue by huajian123** [mobxjs/mobx-angular#189]
Any plans to support Angular 17?

**Comment by Chuckv01** [comment]
@huajian123 Hum, as far as I know the latest version https://github.com/mobxjs/mobx-angular/releases/tag/4.8.0 should already support angular 17? I haven't seen issues with this package on the latest versions of Angular.

If you know of an issue drop more details or a link to a reproduction on this issue plz.
