### ISSUE TITLE
Model driven forms?

### ISSUE THREAD

**Issue by gideoncatz** [mobxjs/mobx-angular#19]
Is it it possible to enhance ng2-mobx to make it work in a model driven template environment?

**Comment by Jonatthu** [comment]
@gideoncatz I think so, but we have reactive form, which right now I'm using for modify the form values then saving to the api and wait for a success response and then update the state, so we need to think if really worth it to change the normal development of forms of angular, for my production project that has a lot of forms this ways is working very well.

**Comment by blackbird529** [comment]
@Jonatthu can you post an example of how you are using mobx with reactive forms.  We are considering using mobx-angular for an upcoming project which has a lot of forms, but I haven't been able to find a good example of how to use a Mobx based model with observable properties with an angular form.

**Comment by Jonatthu** [comment]
@blackbird529 I recommend you to use reactive forms for handle the state of your form.
https://toddmotto.com/reactive-formgroup-validation-angular-2 
and mobx to just update the state if is needed like

```
@action('[USER] [SUBMIT] Try')
public submitNewUser(user: UsermModel) {
    // Handle ajax call
         // On callback change the state
}
```

Anyway soon I will open a blog putting a better example and a user case :)

**Comment by blackbird529** [comment]
Thanks for the quick reply!  So if I am understanding correctly, you could do something like this:
`
@Injectable()
export class Store {
  @observable userModel: UserModel;
  @action submitNewUser(user: UserModel) {
      // code to handle adding a the new user
  }
}

@Component({...})
export class UserComponent implements OnInit {
     user: FormGroup

     constructor(private fb: FormBuilder, private store: Store) { }

     ngOnInit() {
         this.user = this.fb.group({
             userName: [store.userModel.userName, ['Validators.required']],
             ....... //other property bindings
         });
     }

     // method bound to form's submit event.
     onSubmit(userModel: UserModel) {
        //code to extract the user data from the form
        this.store.submitNewUser(userModel);
     }
}
`
The code is a bit rough, but would that be the general idea?  I look forward to seeing your blog post on the topic!

**Comment by Jonatthu** [comment]
@blackbird529 Yes that's working with me we have a big project with a lot of forms too, and is working very well this way :)

**Comment by blackbird529** [comment]
Cool!  I'll give that approach a try then. Thanks @Jonatthu.

**Comment by rbaumi** [comment]
I'm trying to implement mobX into my login page (model driven form) and have some issues with reaction not being triggered.

My store.ts:

```ts
export class UserLoginModel {
    @observable email   : string = '';
    @observable password: string = '';

    constructor() { }
}

@Injectable()
export class UserLoginStore {
    @observable user: UserLoginModel = new UserLoginModel();
    @action loginUser(user: UserLoginModel) {
 
    }
}
```

My login.ts page:

```ts
@IonicPage()
@Component({
    selector       : 'page-login',
    templateUrl    : 'login.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class LoginPage implements OnInit {
    loginForm: FormGroup;

    constructor(
        private _formBuilder       : FormBuilder,
        public userLoginStore: UserLoginStore,
    ) {
    }

    ngOnInit() {
        this.loginForm = this._formBuilder.group({
            email: [this.userLoginStore.user.email, Validators.compose([
                Validators.required,
                EmailValidator.isValid
            ])],
            password: [this.userLoginStore.user.password, Validators.compose([
                Validators.required,
                Validators.minLength(6)
            ])]
        });
    }
}
```

My template:

```html
<ion-content *mobxAutorun>
    <form
        [formGroup]="loginForm"
        (submit)="loginUser()"
    >
        <ion-item
            [class.invalid]="!loginForm.controls.email.valid && loginForm.controls.email.touched"
            [class.valid]="loginForm.controls.email.valid && loginForm.controls.email.touched"
        >
            <ion-label floating>Email</ion-label>
            <ion-input
                formControlName="email"
                type="email"
            >
            </ion-input>
        </ion-item>
        <ion-item
            class="error-message"
            *ngIf="!loginForm.controls.email.valid && loginForm.controls.email.touched"
        >
            <p>Please enter a valid email address.</p>
        </ion-item>

        <ion-item
            [class.invalid]="!loginForm.controls.password.valid && loginForm.controls.password.touched"
            [class.valid]="loginForm.controls.password.valid && loginForm.controls.password.touched"
        >
            <ion-label floating>Password</ion-label>
            <ion-input
                formControlName="password"
                type="password"
            >
            </ion-input>
        </ion-item>
        <ion-item
            class="error-message"
            *ngIf="!loginForm.controls.password.valid && loginForm.controls.password.touched"
        >
            <p>
                Your password needs more than 6 characters.
            </p>
        </ion-item>

        <button
            ion-button
            block
            type="submit"
            [disabled]="!loginForm.valid"
        >
            Log In
        </button>
    </form>
</ion-content>
```

Without *mobxAutorun everything works ok. I can see that the dependecy tree contains only loginForm. Shall I not use the *mobxAutorun with the form? If it's ok then why the form controls state is not updated when input value changes?

**Comment by kunjee17** [comment]
@blackbird529  @Jonatthu . I didn't get one part. Why `UserModel` is observable. I guess you can't modify it from out side of class and if you are passing it via function then it don't required to be observable. 

There is a form plug in NgXS which observe on dirty, status like form property. It would be great if we can achieve same here. Or Am I missing something here in mobx specific approach?

**Comment by adamkleingit** [comment]
Hey,
closing this one. I don't think mobx-angular should handle this.
Form state in Angular is local, so syncing it with a store would be tricky. Updating the entire model on submit sounds more suitable
