### ISSUE TITLE
Export `action` from mobx?

### ISSUE THREAD

**Issue by th0r** [mobxjs/mobx-angular#20]
Hi! Thanks for an amazing module!

I have a small problem with using it with AoT compiler though.
Saw #13 and importing `observable` and `computed` directly from `ng2-mobx` works perfect, but I also need to import `action` to decorate methods that change a bunch of observables, but `ng2-mobx` doesn't export it.

Maybe use `export * from 'mobx'` instead of exporting proxies or AoT will fail in this case as well?

**Comment by adamkleingit** [comment]
I'll try that.
