### ISSUE TITLE
Option to disable the MobxAngularDebug utility in production builds

### ISSUE THREAD

**Issue by returnlytom** [mobxjs/mobx-angular#23]
MobxAngularDebug is very helpful during the development process. But per [Can I Use](http://caniuse.com/#feat=namevalue-storage), approximately ~5% of users are running browsers that do not support Web Storage.  Subsequently, every so often I receive a notification via Sentry that my production app crashed during an instantiation of an observable (which was ultimately triggered by the lack of localStorage support).

Thus, it would be great if there was a build time flag we could use to disable including this utility with the production bundle.

**Comment by adamkleingit** [comment]
Hi @returnlytom ,
That's weird because before accessing localStorage I check if it exists using this line of code:
```
if (typeof localStorage === 'undefined' || typeof console === 'undefined') {
  return;
}  
```
Can you send me the crash report?

**Comment by returnlytom** [comment]
Two examples, with the OS / browser info:

![image](https://user-images.githubusercontent.com/22224829/30082707-a16d32c6-9240-11e7-8c9d-7f65cc5d7f54.png)
```
null is not an object (evaluating 'localStorage["mobx-angular-debug"]')
```

![image](https://user-images.githubusercontent.com/22224829/30082755-ca566a72-9240-11e7-8893-5e963be6eef5.png)

```
Cannot read property 'mobx-angular-debug' of null
```

**Comment by adamkleingit** [comment]
Thanks. So localStorage is null.
I will add that check as well in 1.8.0 - should solve it.

**Comment by adamkleingit** [comment]
Deployed - can you verify?

**Comment by returnlytom** [comment]
Thanks for the fix; will push to production and keep you posted.

**Comment by returnlytom** [comment]
Appears to be working, but now crashing here:
![image](https://user-images.githubusercontent.com/22224829/31190203-47822cc4-a8ef-11e7-8e97-f0fdd11b052a.png)

Seems to be limited to this OS / browser profile:
![image](https://user-images.githubusercontent.com/22224829/31190221-5923366c-a8ef-11e7-9c0d-bfbca429fdc1.png)

**Comment by adamkleingit** [comment]
Pushed to 1.8.1 - can you check?
By the way - does it work in development? What are you doing differently in production build?

**Comment by returnlytom** [comment]
Will do.

Not doing anything different in development; but we don't test on Safari 11 / MacOS 10.12.6
