### ISSUE TITLE
Compatibility with pipes

### ISSUE THREAD

**Issue by gideoncatz** [mobxjs/mobx-angular#26]
Hi,

I was trying to pass an array to angular's standard slice pipe.
That array is a part of a data store service which is injected into that particular component, and is defined with @observable decorator.

So when I try to run this array through the slice pipe, (passing the array, a start index and an end index) I get this:

Invalid argument '[object Object],[object Object],[object Object]' for pipe 'SlicePipe'

The pipe works properly if I remove the @observable decoration.
Please check.

---------------------------------
Update:

Strange. As part of code changes which I did later on, I'm now getting the same error even when the @observable decorator is not present.

Do you have an example of how to properly use arrays marked with @observable in conjunction with pipes?

Thanks,
Gideon

**Comment by adamkleingit** [comment]
Hey,
Can you paste the code of the SlicePipe?

Thanks

**Comment by returnlytom** [comment]
@gideoncatz Perhaps the pipe is expecting a JS Array instead of an Observable Array? https://mobx.js.org/refguide/array.html explains how mobx wraps the standard Array class

**Comment by gideoncatz** [comment]
Thanks for the link, @returnlytom !
Adding a .slice() before the pipe did the trick:

`<li *ngFor="let name of dataStore.getNames().slice() | slice:0:2">{{name}}</li>`
