### ISSUE TITLE
mobxAutorun not working with onPush without  @Input

### ISSUE THREAD

**Issue by naomipol** [mobxjs/mobx-angular#33]
I'm trying to use the mobx in my angular project.
When I use the `*mobxAutorun` directive together with `OnPush` detection, the component does not re-render on changes unless I pass the `@computed` value from the store as an `@Input`.
If I inject the store into the component's constructor and refer to the `@computed` value from the store object in my view - the changes do not reflect the view.

**document-list.ts**
```js
//works!!!
@Component({
  selector: 'dc-list-preview',
  template: `
  	<ion-list *mobxAutorun>
           <dc-preview *ngFor="let document of documents"
             [document]="document">
           </dc-preview>
        </ion-list>
  	`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DocumentListPreview {

  @Input() documents;
}
```

```js
//doesn't work!!!!
@Component({
  selector: 'dc-list-preview',
  template: `
  	<ion-list *mobxAutorun>
            <dc-preview *ngFor="let document of store.documents"
                [document]="document"
                (select)="store.selectDoc(document.id)">
            </dc-preview>
        </ion-list>
  	`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DocumentListPreview {

  constructor(private store: DocumentsStore) {}
}
  ```

**store.ts**
```js
@Injectable()
  export class DocumentsStore {

  @observable documentsObj: {[key: string]: Order} = {};

  @computed get documents(): Order[] {
      return Object.keys(this.documentsObj).map(key => this.documentsObj[key]);
    }

  @action fetch() {
      asyncFetch.then(this,insert)
    }

  @action insert = (data) => {
      data.forEach(doc=> {
        this.documentsObj[doc.id] = doc;
      })
    }
}
```

What am I doing wrong?

**Comment by adamkleingit** [comment]
Hi,
I'll try to look into it in the coming days.

All the best

**Comment by phra** [comment]
@adamkleingit any update?

**Comment by adamkleingit** [comment]
Now I'm seeing the problem.
When using dynamic keys you have to use extendObservable:
```
import { extendObservable } from 'mobx';

data.forEach(doc=> {
  extendObservable(this.documentsObj, {[doc.id]: doc});
});
```
Or use immutable data:
```
data.forEach(doc=> {
  this.documentsObj = {
    ...this.documentsObj,
    [doc.id]: doc
  };
});
```

Otherwise MobX is not aware of the change.

**Comment by mweststrate** [comment]
Best is to use observable maps for dynamically keyed structures. ExtendObservable will propagate changes on already detected keys, but not on new keys. See the [docs](https://mobx.js.org/refguide/map.html) (For the explanation why maps are needed [this](https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/react.md#incorrect-using-not-yet-existing-observable-object-properties))

**Comment by adamkleingit** [comment]
+1 @mweststrate
