### ISSUE TITLE
combine mobx with Rxjs

### ISSUE THREAD

**Issue by naomipol** [mobxjs/mobx-angular#34]
I've read the following [here](https://www.reddit.com/r/javascript/comments/4austh/why_isnt_rxjs_more_popular_are_there_bad_parts/?st=j443wqi9&sh=b491d6ef)

> RxJs helps you deal with events, MobX helps you deal with values (again, like a spreadsheet). You will find that the latter works more intuitively and high-level in most cases. (but combining both is also a very powerful combination)

Since its known that Rxjs Observables are first class citizens in Angular, I wonder if there is a way to combine them together with Mobx's state management?

What are the benefits from doing so? What use cases? Does anyone have a working example?

**Comment by adamkleingit** [comment]
Hi,
MobX works in a different way than RXJS, it always gives you a snapshot of reality, and Rx treats things as a stream of events.
Basically MobX is simpler, and Rx is more flexible (but in most cases you don't need that flexibility).
There's no real way to combine them, but there's also no reason not to use both of them in the same project for different purposes.

BTW, You can always convert them to each other with this lib:
https://github.com/chicoxyzzy/rx-mobx
