### ISSUE TITLE
Getting "Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function"

### ISSUE THREAD

**Issue by skiv1102** [mobxjs/mobx-angular#40]
I'm using angular-tree-component that have dependency on mobx-angular(v1.5.0)
With angular 4.2.6 everything works fine, but with 4.3.0 i keep getting error:

`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in project/node_modules/mobx-angular/node_modules/@angular/core/core.d.ts, resolving symbol MobxAngularModule in project/node_modules/mobx-angular/dist/mobx-angular.d.ts, resolving symbol MobxAngularModule in project/node_modules/mobx-angular/dist/mobx-angular.d.ts`

**Comment by adamkleingit** [comment]
Hi, please open this in angular-tree-component repository.
BTW, try upgraing angular-tree-component to 5.0.0 and see if problem persists (see changelog for breaking changes)
