### ISSUE TITLE
Please help: *mobxAutorun makes the whole component not being rendered

### ISSUE THREAD

**Issue by davidpodhola** [mobxjs/mobx-angular#42]
I must be missing something obvious and I know I use this issue selfishly to get help. 

If I add `*mobxAutorun` on the top of [`tags.component.html`](https://github.com/hsharpsoftware/angular-realworld-example-app/blob/master/src/app/home/tags/tags.component.html#L1), the whole component is not rendered. If I remove it, it is rendered on the bottom of the page, but the the code reflecting to the `commonStore.isLoadingTags` is not processed correctly.

Thanks for your suggestions!

**Comment by adamkleingit** [comment]
Hi,
you need to import MobxAngularModule in SharedModule, not AppModule, and then export it as well so it's available throughout the app:
```
@NgModule({
  imports: [
    ...
    MobxAngularModule
  ],
  ...
  exports: [
    ...
    MobxAngularModule
  ]
})
export class SharedModule {}

```

**Comment by davidpodhola** [comment]
Perfect, thanks a lot!
