### ISSUE TITLE
Does not conform to Angular Package Format

### ISSUE THREAD

**Issue by steveblue** [mobxjs/mobx-angular#51]
The build for this library does not seem to conform to the Package Format 5.0. Please update to conform to the spec so all applications can benefit from this project.

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

**Comment by adamkleingit** [comment]
@steveblue can you say what's missing? Or even better make a PR?
Thanks

**Comment by steveblue** [comment]
@adamkleingit I included a link to the doc. But heres the quick rundown:
- Use 'annotateWithClosureCompiler` in your tsconfig compilerOptions
- Bundle 3 variants, FESM, UMD, and ES5 with ES2015 imports and exports
- Put "main", "module", and "esm2015" properties pointing to bundles in package.json


If I have time, I can package it and submit a PR (assuming I don't run into too many TS errors) but with the holidays not looking likely.

**Comment by adamkleingit** [comment]
This is fixed in the latest version - we switched to `ng generate lib`
