### ISSUE TITLE
When upgrading to v.2.0.1, Agnular Material fails to execute properly

### ISSUE THREAD

**Issue by Shyam-Chen** [mobxjs/mobx-angular#52]
https://github.com/Shyam-Chen/Angular-Fullstack-Starter/blob/master/src/app/form-controls/template-driven/template-driven.component.ts#L15

After upgrading to v.2.0.1, Angular Material input can not focus.

**Comment by adamkleingit** [comment]
Try using *mobxAutorun="{ dontDetach: true }"

**Comment by Shyam-Chen** [comment]
Thanks. Work for me.
