### ISSUE TITLE
Allow to remove the warning message in console

### ISSUE THREAD

**Issue by adamkleingit** [mobxjs/mobx-angular#53]
Some developers might not appreciate having a console warning imposed on them.

**Comment by mbenzenhoefer** [comment]
+1 for this issue, we do not like log messages in production code
`Type mobxAngularDebug(true) or mobxAngularDebug(false) to trigger MobX debugging`

see the original issue for it (https://github.com/500tech/angular-tree-component/issues/496)

**Comment by LanderBeeuwsaert** [comment]
Jep, same here.

**Comment by Reboca** [comment]
+1 need help

**Comment by finalxcode** [comment]
+1  same here.

**Comment by mbenzenhoefer** [comment]
What do you think how this might be resolved? The easiest way would be to remove the message and just put the hint to the docs. I could create a PR for this.

**Comment by mbenzenhoefer** [comment]
PR #57

**Comment by adamkleingit** [comment]
Merged
