### ISSUE TITLE
Integration of mobx with remotedev for inspect state in the redux devtools

### ISSUE THREAD

**Issue by pedrotainha** [mobxjs/mobx-angular#56]
Hi @Jonatthu, i'm not sure this could be an issue of mobx-angular, but i'm not able to put this working and i saw a similar issue in this repo (https://github.com/mobxjs/mobx-angular/issues/17) but didn't help me.

I just grab your **bank** example, then:
- npm install
- npm install --save mobx-remotedev
- change code in file: account.store.ts to

```
import { Injectable } from '@angular/core';
import { observable, autorun, computed, action, reaction, when, toJS, useStrict } from 'mobx';
import { sum } from 'lodash';
import remotedev from 'mobx-remotedev'; //added this line

useStrict(true);


@remotedev({name: 'MY STORE', global: true}) //added this line
@Injectable()
export class Account {
  @observable transactions: number[] = [];

  constructor() {
    if (localStorage.savedTransactions) {
      this.transactions = JSON.parse(localStorage.savedTransactions);
...
```
then i run ng serve and i open the redux console in browser, refresh the page i can't see the store.

Any tip on this? Thanks in advance.

**Comment by adamkleingit** [comment]
I managed to make it work like this:

todos.store.ts:
```
@Injectable()
export class Todos {
  ...
}
```

app.module.ts:
```
import remotedev from 'mobx-remotedev/lib/dev';

...
    providers: [{ provide: Todos, useClass: remotedev(Todos) }],
...
```
Sometimes you need to refresh / send an action to see the store in the devtools.

Tell me if it works for you and I'll update the docs

**Comment by pedrotainha** [comment]
Hi thanks for your time.

Yes it works. I tried first with the import like this:

`import remotedev from 'mobx-remotedev';`

but it only works like this (do you know why? Thanks in advance): 

`import remotedev from 'mobx-remotedev/lib/dev';`

**Comment by adamkleingit** [comment]
Not sure, maybe it's a question to mobx-remotedev team?
