### ISSUE TITLE
What about extending from an ObserverComponent class?

### ISSUE THREAD

**Issue by hccampos** [mobxjs/mobx-angular#71]
Just for fun I have been messing around with Angular and trying to make MobX work with it in a more transparent way. I came up with this: 

https://stackblitz.com/edit/angular-4yilqu?embed=1&file=src/app/app.component.ts

You can extend `ObserverComponent` which automatically wraps all the inputs so they are detected by MobX and can be used in `computed`s. It also automatically injects the `ChangeDetectorRef` to trigger change detection in the component whenever any MobX observable changes. No need for `ng-containter`s or `*mobxAutorun`.

One drawback is that if a component injects stuff, it needs to inject the `ChangeDetectorRef` as well and pass it to the base class via `super`. And if a component implements `ngOnDestroy` or `ngAfterViewInit` it needs to call them on the base class as well.

Imho, the drawbacks probably make this solution worse that the one implemented in `mobx-angular`. However, it is fun to think about it and maybe in the future Angular will support adding directives as a decorator to a component or in the `host` property of the `Component` decorator which would make everything work much more like in `mobx-react`

**Comment by adamkleingit** [comment]
@hccampos, yes I deliberated a lot about this. Mainly because of superclasses etc. I decided to go for the simpler solution of a directive (it also gives you the flexibility of having multiple observed sections inside a single component.
BTW about your code - why doesn't observeInput use extendObservable?
