### ISSUE TITLE
Mobx configuration

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [mobxjs/mobx-angular#74]
Hello,

I'm tried to use multiple mobx(with multi app) in a single zone in a single-spa application but I can't work out the multiple instance error.  If I'm right I can set isolateGlobalState: true to work it well, but I don't know how to.

I've tried in my main module:

> import { configure } from 'mobx';
> ...
> configure({ isolateGlobalState: true });

But it is not working.

So my question is how to configure mobx.
Is there any workaround for multiple instance issue, I've tried anything I found in 1082 issue.

Thank you!

Norbert

**Comment by adamkleingit** [comment]
@ssi-hu-tasi-norbert have you found a solution? I have never tried this scenario.
If you solve it I would love a PR

**Comment by ssi-hu-tasi-norbert** [comment]
Hi Adam!

To be honest I can't recall it. I went to different direction because the spa was not as stable as it should be. I couldn't find anything in the code but what I wrote above. I assume it was not the solution. It is possible that it was one of the reasons of changing ways.
