### ISSUE TITLE
Uncaught ReferenceError: mobxAngularDebug is not defined 

### ISSUE THREAD

**Issue by aaronksaunders** [mobxjs/mobx-angular#76]
Getting this error when trying to use dev tools? 

```
    "mobx": "5.5.0",
    "mobx-angular": "3.0.1",
    "mobx-devtools": "0.9.20",
    "mobx-remotedev": "^0.2.8",
```

**Comment by aaronksaunders** [comment]
i thought it was related to stackblitz but still fails when in new window

**Comment by adamkleingit** [comment]
Hi @aaronksaunders, I couldn't reproduce it - can you send a Stackblitz link?
Thanks

**Comment by adamkleingit** [comment]
I don't see that error in the console. Are you seeing this error in mobx devtools chrome extension?
Are you using mobx-devtools or mobx-remotedev? I saw both of them in package.json.

This used to be an error in old versions but it was supposed to be fixed

**Comment by aaronksaunders** [comment]
it looks like it is my bad for not reading the doc

> **Debugging MobX (only for mobx-angular versions 2.X and below)**
> mobx-angular comes with a handy debug tool. To turn on / off the debug tool, open developer tools' console, and run:

i will close this and open another issue because i cannot get the remote dev tools working either
