### ISSUE TITLE
ViewChild breaks with Mobxautorun

### ISSUE THREAD

**Issue by shaunpatterson** [mobxjs/mobx-angular#80]
Given a component's html
```
<div *mobxAutorun>
      ... input fields ... 
       <app-address #mailingAddress></app-address>
      ... input fields ... 
</div>
```

and

`@ViewChild('mailingAddress')
mailingAddress: AddressComponent`

in the component

mailingAddress is undefined.  If I move the *mobxAutorun one level above (ie, the parent component) or remove *mobxAutorun, mailingAddress works as expected

**Comment by shaunpatterson** [comment]
Well, this appears to be by design, since the directive is creating a subview (hence why the ViewChild doesn't work).

I presume the idea here would be to move the directive into my address component and then apply the directive to the other parts of my form?

**Comment by adamkleingit** [comment]
@shaunpatterson what is the error? If I try it in the example code with a simple span inside the *mobxAutorun - then it works well.

**Comment by shaunpatterson** [comment]
Given this, and popping <app-test> into my application

```
@Component({
  selector: 'app-test',
  template: `
    <div *mobxAutorun>
        <app-test2 #test2></app-test2>        
    </div>
  `
})
export class TestComponent implements OnInit {

  @ViewChild('test2')
  test2: Test2Component;

  constructor() {}

  ngOnInit() {
    debugger;    // RIGHT HERE
  }
}

@Component({
  selector: 'app-test2',
  template: `<span>Test</span>`
})
export class Test2Component implements OnInit {

  constructor() {}

  ngOnInit() {

  }
}
```

At the debugger statement, this.test2 is undefined.  

If I remove `    <div *mobxAutorun>` and make it just `<div>`, test2 is now defined correctly

**Comment by 500tech-user** [comment]
try ngAfterViewInit

**Comment by shaunpatterson** [comment]
Yeah ngAfterViewInit works.  But essentially I have to build my form with an empty validator for this address component and then later augment the form with the formgroup from the address component once it's rendered.

**Comment by adamkleingit** [comment]
Yeah, it's a general Angular forms question I guess.
