### ISSUE TITLE
Is mobx-angular works with angular ^7?

### ISSUE THREAD

**Issue by Mooli88** [mobxjs/mobx-angular#81]
Important!

In case you are reporting a bug, or requesting help, please reproduce it in a GIT repo or fork this online template:
https://stackblitz.com/edit/angular-usygae?file=app%2Fapp.component.html

If you are unable to reproduce, please:
- paste your package.json
- say which browser you are using
- paste your nodes and options and whatever code your feel will help reproduce the error

Thank you and happy programming

**Comment by adamkleingit** [comment]
It works.
Just updated the todos example to use 7.
