### ISSUE TITLE
[mobx] Incorrect decorator invocation.

### ISSUE THREAD

**Issue by gs-trader** [mobxjs/mobx-angular#85]
**Configuration** 
"mobx": "^4.3.1",
"mobx-react": "^5.2.3

**Issue**

i have an object marked observable like
`@observable form ={}`

but later in a code i want to mark as value as flat as follows:
```
let newValue = [...this.form.fields[myFieldname].value];
const flatVal = { fileName: value.fileName, content: observable.ref(value.content) }
```
But in the above i get error: 

> [mobx] Incorrect decorator invocation. @observable decorator doesn't expect any arguments

To conclude. i want to mark a value unobservable/asFlat, given its parent is an observable when initialized.

can somebody please explain how to achieve it.

**Comment by adamkleingit** [comment]
Looks like a pure MobX question, not mobx-angular one.
@mweststrate ?
