### ISSUE TITLE
Option to use mobx-angular in AngularDart?

### ISSUE THREAD

**Issue by radzish** [mobxjs/mobx-angular#88]
What is the best way of doing this?
I was trying to port MobxAutorunDirective to Dart and had some success, but I am concerned with the fact that ChangeDetectorRef.detectChanges() method is marked as deprecated. Is there any other way to implement Directive properly ?

**Comment by adamkleingit** [comment]
Hi,
I have never tried. Do you have a link to a public repo that you can share so I can have a look?

Thanks

**Comment by radzish** [comment]
Hi, see here:

https://github.com/radzish/mobx_dart_angular/blob/master/lib/src/mobx_autorun_directive.dart

**Comment by adamkleingit** [comment]
I don't see that detectChanges is deprecated in the regular docs. Is it different in the dart version?

**Comment by radzish** [comment]
Yes, it is deprecated in dart version, see here: https://angulardart.dev/api/angular/angular/ChangeDetectorRef-class

**Comment by adamkleingit** [comment]
If anyone wants to create a PR for this anyway I'll be happy to assist and review. Closing it until there's any new activity
