### ISSUE TITLE
How to use mobx with remote data?

### ISSUE THREAD

**Issue by mgordic** [mobxjs/mobx-angular#89]
Hi,

I want to use mobx for some automatic data calculations.

If I bind a component to class instance that is instantiated in ngOnInit for example, everything works fine and when I change input fields, calculated properties are updated and displayed in UI.

However, if I get the data from back end first with HttpClient and promise, calculations are not reacting anymore and there are no errors in console.

Any ideas?

**Comment by adamkleingit** [comment]
Can you share a code sample?
Every change to a mobx observable should invoke all the observed computed values and reactions, so it doesn't really matter if it's from a promise or not.
