### ISSUE TITLE
Failure with latest Angular

### ISSUE THREAD

**Issue by mgechev** [mobxjs/mobx-angular#93]
Because of the type definitions in `mobx-autorun-sync.directive.d.ts` and the removal of the deprecated `Renderer`, `mobx-angular` no longer works with the latest `@angular/core`.

You can find the failure in the CI [here](https://circleci.com/gh/mgechev/ngcc-validation/101).

In the official version 9 release, we'll no longer have `Renderer` part of Angular.

**Comment by adamkleingit** [comment]
Will be fixed in 3.0.2. The Renderer is not being used anyway

**Comment by mgechev** [comment]
Sounds great!

**Comment by mgechev** [comment]
@adamkleingit how's the release going? Do you think you'll be able to publish it before the next week when we have our RC scheduled for?

**Comment by adamkleingit** [comment]
Updated 3.0.2
